using UAPS.SDK.Client;

namespace UAPS.CLI.Tsv;

/// <summary>
/// TSV (Tab-Separated Values) output file writer
/// </summary>
public class TsvOutputWriter
{
    /// <summary>
    /// Write schedule results to TSV file
    /// </summary>
    public void Write(string filePath, Schedule schedule)
    {
        using var writer = new StreamWriter(filePath);

        // Write header
        writer.WriteLine("# Schedule Results - Generated by U-APS");
        writer.WriteLine($"# Makespan: {schedule.MakespanMs}ms");
        writer.WriteLine();

        // Write assignments section
        writer.WriteLine("[ASSIGNMENTS]");
        writer.WriteLine(string.Join("\t", new[]
        {
            "OPERATION_ID",
            "RESOURCE_ID",
            "START_MS",
            "END_MS",
            "DURATION_MS"
        }));

        foreach (var assignment in schedule.Assignments)
        {
            writer.WriteLine(string.Join("\t", new object[]
            {
                assignment.OperationId,
                assignment.ResourceId,
                assignment.StartMs,
                assignment.EndMs,
                assignment.DurationMs
            }));
        }

        writer.WriteLine();

        // Write violations section if any
        if (schedule.Violations.Count > 0)
        {
            writer.WriteLine("[VIOLATIONS]");
            writer.WriteLine(string.Join("\t", new[]
            {
                "TARGET_ID",
                "TYPE",
                "AMOUNT",
                "DESCRIPTION"
            }));

            foreach (var violation in schedule.Violations)
            {
                writer.WriteLine(string.Join("\t", new object[]
                {
                    violation.TargetId,
                    violation.ConstraintType,
                    violation.Amount,
                    violation.Description
                }));
            }
        }
    }

    /// <summary>
    /// Write schedule results to TSV directory (separate files)
    /// </summary>
    public void WriteDirectory(string directoryPath, Schedule schedule)
    {
        if (!Directory.Exists(directoryPath))
        {
            Directory.CreateDirectory(directoryPath);
        }

        // Write assignments
        WriteAssignmentsFile(Path.Combine(directoryPath, "assignments.tsv"), schedule.Assignments);

        // Write violations if any
        if (schedule.Violations.Count > 0)
        {
            WriteViolationsFile(Path.Combine(directoryPath, "violations.tsv"), schedule.Violations);
        }

        // Write summary
        WriteSummaryFile(Path.Combine(directoryPath, "summary.tsv"), schedule);
    }

    private void WriteAssignmentsFile(string filePath, List<Assignment> assignments)
    {
        using var writer = new StreamWriter(filePath);

        writer.WriteLine(string.Join("\t", new[]
        {
            "OPERATION_ID",
            "RESOURCE_ID",
            "START_MS",
            "END_MS"
        }));

        foreach (var assignment in assignments)
        {
            writer.WriteLine(string.Join("\t", new object[]
            {
                assignment.OperationId,
                assignment.ResourceId,
                assignment.StartMs,
                assignment.EndMs
            }));
        }
    }

    private void WriteViolationsFile(string filePath, List<Violation> violations)
    {
        using var writer = new StreamWriter(filePath);

        writer.WriteLine(string.Join("\t", new[]
        {
            "TARGET_ID",
            "TYPE",
            "AMOUNT",
            "DESCRIPTION"
        }));

        foreach (var violation in violations)
        {
            writer.WriteLine(string.Join("\t", new object[]
            {
                violation.TargetId,
                violation.ConstraintType,
                violation.Amount,
                violation.Description
            }));
        }
    }

    private void WriteSummaryFile(string filePath, Schedule schedule)
    {
        using var writer = new StreamWriter(filePath);

        writer.WriteLine("METRIC\tVALUE");
        writer.WriteLine($"MAKESPAN_MS\t{schedule.MakespanMs}");
        writer.WriteLine($"ASSIGNMENT_COUNT\t{schedule.Assignments.Count}");
        writer.WriteLine($"VIOLATION_COUNT\t{schedule.Violations.Count}");
    }
}
